#!/usr/bin/env php
<?php

$projectName = basename(getcwd());

exec('vendor\bin\codecept run -q -n', $output, $returnCode);

if ($returnCode !== 0) {
    printf("ABORTING Push!\n");
    exit(1);
}

exit(0);