#!/usr/bin/env php
<?php

$projectName = basename(getcwd());

exec('vendor\bin\codecept run --no-colors -n --html', $output, $returnCode);

if ($returnCode !== 0) {
    //We will fetch the generated HTML page with all test results and print it to the message
	$html = array_pop($output);
    $minimalTestSummary = array_pop($output);
    printf("Codeception Test suite for %s failed: ", $projectName);
    printf("( %s ) %s", $minimalTestSummary, PHP_EOL);
    printf("%s %s", $html, PHP_EOL);
    printf("ABORTING Push!\n");
    exit(1);
}

exit(0);