#!/usr/bin/env php
<?php
//Run codeception tests and abort on fail
$projectName = basename(getcwd());

exec('vendor\bin\codecept run -n -q -f', $output, $returnCode);

if ($returnCode !== 0) {
    exit(1);
}
exit(0);