version: "2"
services:

  phpfpm:
    build:
     context: docker
     args:
      - PHP_VERSION=${PHP_VERSION}
     dockerfile: DockerfileTests
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    environment:
     - APPLICATION_ENV=${APPLICATION_ENV}
     - PHP_VERSION=${PHP_VERSION}
    volumes:
     - ./:/app
     - ./docker/tmp/logs:/var/log/php
     - ./docker/conf/php/www.conf:/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf
    external_links:
     - "nginx-proxy"
    network_mode: "bridge"
    restart: always

  web:
    image: objectsystems/nginx:1.11.12
    container_name: ${COMPOSE_PROJECT_NAME}-web
    hostname: ${HOST_NAME}
    expose:
     - "80"
     - "443"
    environment:
     - HOST_NAME=${HOST_NAME}
     - VIRTUAL_HOST=${HOST_NAME},www.${HOST_NAME}
     - VIRTUAL_PORT=443
     - WAIT_HOSTS=phpfpm:9000
    volumes:
     - ./:/app
     - ./docker/tmp/logs:/var/log/nginx
     - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./docker/conf/nginx/restrict.conf:/etc/nginx/snippets/restrict.conf
     - ./docker/conf/nginx/web.template:/etc/nginx/conf.d/default.template
    links:
     - "phpfpm"
    external_links:
     - "nginx-proxy"
    command: /bin/ash -c "envsubst '$$HOST_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && /opt/wait.sh && nginx -g 'daemon off;'"
    network_mode: "bridge"
    restart: always

networks:
  default:
    external:
      name: bridge
